[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000

# Uncomment below if you have client-side routing (e.g., React Router)
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
